### ISSUE TITLE
Update Installation Guide (Wiki)

### ISSUE THREAD

**Issue by dnltz** [SpinalHDL/SpinalCrypto#14]
@Snoopy87 How can someone update the wiki?

The installation guide is in the wrong order and sbt uses now "publishLocal" AFAIK.
```
# Get the last version of SpinalCrypto
git clone https://github.com/SpinalHDL/SpinalCrypto.git
git pull origin master
cd SpinalCrypto
sbt publish-local 
```
should be
```
# Get the last version of SpinalCrypto
git clone https://github.com/SpinalHDL/SpinalCrypto.git
cd SpinalCrypto
git pull origin master
sbt publishLocal 
```

BTW: I think the `git pull origin master` is not necessary and can be removed.

**Comment by Dolu1990** [comment]
Just added https://github.com/SpinalHDL/SpinalCrypto/wiki/Getting-started#using-the-library-without-publishlocal ^^

**Comment by dnltz** [comment]
thanks :)
